### ISSUE TITLE
AnsiConsole.Write(string) throws an error when passed a JSON string.

### ISSUE THREAD

**Issue by ashscodes** [spectreconsole/spectre.console#1123]
**Information**
 - OS: Windows 10 and Ubuntu 22.04 (WSL)
 - Version: 0.45.0
 - Terminal: Windows Terminal

**Describe the bug**

When using `AnsiConsole.Write(string)` with a JSON string a `FormatException` is thrown. It appears this happens because the string is passed on to another method that uses `string.Format` despite the initial method requiring no arguments.

**To Reproduce**

Create a new project:

```
mkdir AnsiConsole.Test
dotnet new console -n AnsiConsole.Test -o .\AnsiConsole.Test\
dotnet add .\AnsiConsole.Test\ package Spectre.Console
```

Replace the code in `Program.cs` with:

```csharp
// See https://aka.ms/new-console-template for more information
using Spectre.Console;

string testJson = "{\"id\":\"some-id\",\"name\":\"Hello World\"}";
AnsiConsole.Write(testJson);
```

Run the project:

```
dotnet run --project .\AnsiConsole.Test\
```

**Expected behavior**

Method should not throw a `FormatException`, because the user is not expecting further formatting to occur if they only pass a string.

**Screenshots**

Error Details
```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Spectre.Console.AnsiConsole.Write(IFormatProvider provider, String format, Object[] args) in /_/src/Spectre.Console/AnsiConsole.Write.cs:line 247
   at Spectre.Console.AnsiConsole.Write(String format, Object[] args) in /_/src/Spectre.Console/AnsiConsole.Write.cs:line 235
   at Spectre.Console.AnsiConsole.Write(String value) in /_/src/Spectre.Console/AnsiConsole.Write.cs:line 14
   at Program.<Main>$(String[] args) in .\AnsiConsole.Test\Program.cs:line 5
```

**Additional context**

**Comment by realrubberduckdev** [comment]
In case it helps anyone, I used the following workaround (or possibly that is the recommended way?):

Add package reference to nuget package: [Spectre.Console.Json](https://www.nuget.org/packages/Spectre.Console.Json/0.47.0)

Then use `JsonText` object. The syntax provided in the dos example:
```
AnsiConsole.Write(
    new JsonText(json)
        .BracesColor(Color.Red)
        .BracketColor(Color.Green)
        .ColonColor(Color.Blue)
        .CommaColor(Color.Red)
        .StringColor(Color.Green)
        .NumberColor(Color.Blue)
        .BooleanColor(Color.Red)
        .NullColor(Color.Green));
```
Refer - https://spectreconsole.net/widgets/json

**Comment by patriksvensson** [comment]
@ashscodes Spectre.Console uses formatting under the hood. So you will need to treat the string the same way as you would if you used `string.Format` and escape the curly braces as well.

The following should work:

```csharp
string testJson = "{{\"id\":\"some-id\",\"name\":\"Hello World\"}}";
```
