### ISSUE TITLE
NullReferenceException in Progress

### ISSUE THREAD

**Issue by thomhurst** [spectreconsole/spectre.console#1334]
**Information**
 - OS: MacOS
 - Version: [e.g. 0.47.0]
 - Terminal: GitHub Actions

**Describe the bug**
```
Unhandled 
  exception. System.NullReferenceException: Object reference not set to an 
  instance of an object.
     at Spectre.Console.FallbackProgressRenderer.Update(ProgressContext context) 
  in 
  /_/src/Spectre.Console/Live/Progress/Renderers/FallbackProgressRenderer.cs:line 
  30
     at Spectre.Console.ProgressContext.Refresh() in 
  /_/src/Spectre.Console/Live/Progress/ProgressContext.cs:line 71
     at Spectre.Console.ProgressRefreshThread.Run() in 
  /_/src/Spectre.Console/Live/Progress/ProgressRefreshThread.cs:line 45
     at System.Threading.Thread.StartHelper.Callback(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext 
  executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location ---
     at System.Threading.Thread.StartCallback()
```

**Comment by patriksvensson** [comment]
@thomhurst Thanks for reporting this.
Could you add some kind of reproduction for the error you're experiencing?

**Comment by thomhurst** [comment]
I haven't managed to reproduce it. It's probably happened once out of 1000 times, so not sure what the problem is. I expect some sort of race condition?
