### ISSUE TITLE
Optionally include stack trace when rendering exception

### ISSUE THREAD

**Issue by gitfool** [spectreconsole/spectre.console#385]
**Is your feature request related to a problem? Please describe.**
[CommandApp.GetRenderableErrorMessage](https://github.com/spectreconsole/spectre.console/blob/91f910326c1e0143fa9dae2602f935d102f29452/src/Spectre.Console/Cli/CommandApp.cs#L122) renders the exception message _without_ the stack trace.

**Describe the solution you'd like**
_Optionally_ include stack trace; ideally in a "pretty" format too.

**Describe alternatives you've considered**
Setting [PropagateExceptions](https://github.com/spectreconsole/spectre.console/blob/91f910326c1e0143fa9dae2602f935d102f29452/src/Spectre.Console/Cli/CommandApp.cs#L108) is a workaround but the result is still a little ugly as the pretty message does not end with a newline.

**Comment by phil-scott-78** [comment]
I'm not sure we'll expose the default error message display with a stack trace, even optionally. Not too many security audits are going to pass with that kind of information leaking so that feels like a non-starter. BUT that leads to the next problem that you pointed out - if someone wants to do that, we are making it tough.

Given a simple try catch I'd expect this to just output the pretty format of the exception

```csharp
try
{
    await app.RunAsync(args);
}
catch (Exception e)
{
    AnsiConsole.WriteException(e);
}
```

My output is 
![image](https://user-images.githubusercontent.com/2447331/115814981-1e2b3e00-a3c4-11eb-9577-84e5c288531d.png)

Which includes that extra "Error: uh oh" before we output the exception. 

Feels like if we are throwing the exception that should happen before the call to print the results of `GetRenderableErrorMessage` and let the user handle the output entirely.

**Comment by gitfool** [comment]
Being optional, and defaulting to false, is safer but still let's the user of the library control their own fate. 😛 

Yeah that's what I meant by it's ugly when the exception propagates. `AnsiConsole.WriteException` looks really nice! Does it play nice if the terminal doesn't support ansi? I'd be happy if an optional flag uses that if set, then I wouldn't propagate exceptions anyway.

**Comment by patriksvensson** [comment]
@gitfool Yes, `AnsiConsole.WriteException` works in non-ansi terminals as well.

**Comment by phil-scott-78** [comment]
@gitfool, the change where we aren't displaying the error when `PropagateExceptions` is now in the latest preview build.

I wanted to clarify why I'm hesitant to really build out much in the way of error handling at the `CommandApp` level. Those exceptions really should be those that occur while building the infrastructure of executing a command. Parsing the settings, doing DI, etc. 

Application level unhandled exceptions should be handled at the Command level. I always treat each Command like its own `Main()`. If an unhandled exception occurs, we'll want access to the settings, context, etc which wouldn't be available at the `Main()` level. Building out the `CommandApp` exception handling support any further than what it already is might encourage people to handle exceptions there rather than a more appropriate spot. 

With the way commands are designed, there is of course the possibility of creating a base class that commands inherit from that could handle cross cutting concerns too. Or even move them into an interceptor.

**Comment by gitfool** [comment]
@phil-scott-78 thanks for the detailed explanation, which makes sense, and with your fix I can still control the output from the outside so I'm happy. 😁

**Comment by gitfool** [comment]
@phil-scott-78 fwiw, it looks like interceptors could not be used here since they're only called [before](https://github.com/spectreconsole/spectre.console/blob/b568098d5e6f7d34beaf11db6c091438f631d48a/src/Spectre.Console/Cli/Internal/CommandExecutor.cs#L102) the command is executed.

**Comment by gitfool** [comment]
I have to admit I'm still struggling to be happy with error / exception messages as there are still times when a stack trace is important. Consider an issue with dependency injection:
```
Error: Could not resolve type 'Pharos.Gemini.DeployCommand'.
```
Not very helpful compared to the propagated exception put through `AnsiConsole.WriteException`:
```
Spectre.Console.Cli.CommandRuntimeException: Could not resolve type 'Pharos.Gemini.DeployCommand'.
    System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
      at Pharos.Gemini.HostBuilderExtensions.<>c.<ConfigureServices>b__1_1(Config config) in HostBuilderExtensions.cs:48
      at Microsoft.Extensions.Options.PostConfigureOptions`1.PostConfigure(String name, TOptions options)
      at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
      at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
      at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
      at System.Lazy`1.CreateValue()
      at System.Lazy`1.get_Value()
      at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
      at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
      at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
      at Pharos.Gemini.DeployCommand..ctor(IOptions`1 options, ILogger`1 logger, IServiceProvider serviceProvider) in DeployCommand.cs:19
      at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
      at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
      at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
      at Pharos.Gemini.HostTypeResolver.Resolve(Type type) in HostTypeResolver.cs:21
      at Spectre.Console.Cli.TypeResolverAdapter.Resolve(Type type) in TypeResolverAdapter.cs:25
  at Spectre.Console.Cli.TypeResolverAdapter.Resolve(Type type) in TypeResolverAdapter.cs:43
  at Spectre.Console.Cli.CommandTree.CreateCommand(ITypeResolver resolver) in CommandTree.cs:29
  at Spectre.Console.Cli.CommandExecutor.Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in CommandExecutor.cs:107
  at Spectre.Console.Cli.CommandExecutor.Execute(IConfiguration configuration, IEnumerable`1 args) in CommandExecutor.cs:84
  at Spectre.Console.Cli.CommandApp.RunAsync(IEnumerable`1 args) in CommandApp.cs:87
  at Pharos.Gemini.HostBuilderExtensions.RunCommandAsync(IHostBuilder hostBuilder, String[] args) in HostBuilderExtensions.cs:71
```
But then you don't always want such an exception message for say omitting a required argument:
```
Spectre.Console.Cli.CommandRuntimeException: Command 'deploy' is missing required argument 'environment'.
  at Spectre.Console.Cli.CommandValidator.ValidateRequiredParameters(CommandTree tree) in CommandValidator.cs:17
  at Spectre.Console.Cli.CommandValueResolver.GetParameterValues(CommandTree tree, ITypeResolver resolver) in CommandValueResolver.cs:14
  at Spectre.Console.Cli.CommandBinder.Bind(CommandTree tree, Type settingsType, ITypeResolver resolver) in CommandBinder.cs:9
  at Spectre.Console.Cli.CommandExecutor.Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in CommandExecutor.cs:103
  at Spectre.Console.Cli.CommandExecutor.Execute(IConfiguration configuration, IEnumerable`1 args) in CommandExecutor.cs:84
  at Spectre.Console.Cli.CommandApp.RunAsync(IEnumerable`1 args) in CommandApp.cs:87
  at Pharos.Gemini.HostBuilderExtensions.RunCommandAsync(IHostBuilder hostBuilder, String[] args) in HostBuilderExtensions.cs:66
```
Where the standard message suffices:
```
Error: Command 'deploy' is missing required argument 'environment'.
```
Or how about passing an invalid argument that cannot be converted to the underlying type:
```
System.FormatException: abc is not a valid value for Environment.
     System.ArgumentException: Requested value 'abc' was not found.
       at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
       at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
       at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
       at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
       at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
  at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
  at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
  at Spectre.Console.Cli.CommandValueResolver.GetParameterValues(CommandTree tree, ITypeResolver resolver) in CommandValueResolver.cs:92
  at Spectre.Console.Cli.CommandBinder.Bind(CommandTree tree, Type settingsType, ITypeResolver resolver) in CommandBinder.cs:9
  at Spectre.Console.Cli.CommandExecutor.Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in CommandExecutor.cs:103
  at Spectre.Console.Cli.CommandExecutor.Execute(IConfiguration configuration, IEnumerable`1 args) in CommandExecutor.cs:84
  at Spectre.Console.Cli.CommandApp.RunAsync(IEnumerable`1 args) in CommandApp.cs:87
  at Pharos.Gemini.HostBuilderExtensions.RunCommandAsync(IHostBuilder hostBuilder, String[] args) in HostBuilderExtensions.cs:66
```
Where the standard message suffices again:
```
Error: abc is not a valid value for Environment.
```
Finally, for the record, here's what an unhandled exception looks like that originates from inside a command handler:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at Pharos.Gemini.DeployCommand.ExecuteAsync(CommandContext context, Settings settings) in DeployCommand.cs:55
  at Spectre.Console.Cli.AsyncCommand`1.Spectre.Console.Cli.ICommand.Execute(CommandContext context, CommandSettings settings) in AsyncCommandOfT.cs:42
  at Spectre.Console.Cli.CommandExecutor.Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in CommandExecutor.cs:115
  at Spectre.Console.Cli.CommandExecutor.Execute(IConfiguration configuration, IEnumerable`1 args) in CommandExecutor.cs:84
  at Spectre.Console.Cli.CommandApp.RunAsync(IEnumerable`1 args) in CommandApp.cs:87
  at Pharos.Gemini.HostBuilderExtensions.RunCommandAsync(IHostBuilder hostBuilder, String[] args) in HostBuilderExtensions.cs:71
```
If this was caught inside the handler the stack would look like the following instead:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at Pharos.Gemini.DeployCommand.ExecuteAsync(CommandContext context, Settings settings) in DeployCommand.cs:57
```
Anyway, if I'm resigned to propagate all exceptions so that I can have more control of when to show a stack trace, and when not to, how should I differentiate these exceptions to get the best results? Thoughts?

**Comment by phil-scott-78** [comment]
The way I handle exceptions.

1) Put `PropagateExceptions` in a `#IF DEBUG` block to make sure I only do that when developing. This helps with the runtime exceptions like DI and my screw ups.
2) Per command have a try / catch block that handles them at that level. I treat each command like its own little application and I rarely rethrow from those commands. For unhandled exceptions at the command level, I use serilog for logging them to a text file, display a small message and return an error code.

One thing I've been meaning to do is maybe wrap up that functionality into a base class for all my commands in my own project, but with everyone's needs being wildly different here that's best done by the dev I think.

At this point application failures are handled per command, during production any unhandled application errors like poorly formatted arguments are simply printed to the screen, and during development I get full stack trace.

**Comment by gitfool** [comment]
@phil-scott-78 thanks for the thoughts.
1. _not sufficient_ for runtime errors in production, which in this case happen with dynamic per environment configuration
2. I ended up creating some base classes with common boilerplate for sync and async commands; e.g.:
```c#
public abstract class AsyncCommandBase<TSettings> : AsyncCommand<TSettings> where TSettings : CommandSettings
{
    protected AsyncCommandBase(IOptions<Config> options, ILogger logger)
    {
        Config = options.Value;
        Logger = logger;
    }

    public override async Task<int> ExecuteAsync(CommandContext context, TSettings settings)
    {
        try
        {
            return await OnExecuteAsync(context, settings);
        }
        catch (Exception ex)
        {
            AnsiConsole.WriteException(ex, ExceptionFormats.ShortenPaths);
            return -1;
        }
    }

    protected abstract Task<int> OnExecuteAsync(CommandContext context, TSettings settings);

    protected Config Config { get; }
    protected ILogger Logger { get; }
}
```
