### ISSUE TITLE
AnsiConsole.Render(table) may throw ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by phaselden** [spectreconsole/spectre.console#501]
**Information**
 - OS: Windows 10
 - Version: 0.41.0
 - Terminal: cmd

**Describe the bug**
Sometimes, if the console window size is just right, an exception is thrown when calling Render().

(sorry, I don't have time today to track down the issue further)

**Additional context**
Stack trace:

```
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Spectre.Console.Rendering.Segment.SplitOverflow(Segment segment, Nullable`1 overflow, Int32 maxWidth) in /_/src/Spectre.Console/Rendering/Segment.cs:line 340
   at Spectre.Console.Paragraph.SplitLines(Int32 maxWidth) in /_/src/Spectre.Console/Widgets/Paragraph.cs:line 244
   at Spectre.Console.Paragraph.Render(RenderContext context, Int32 maxWidth) in /_/src/Spectre.Console/Widgets/Paragraph.cs:line 150
   at Spectre.Console.Rendering.Renderable.Spectre.Console.Rendering.IRenderable.Render(RenderContext context, Int32 maxWidth) in /_/src/Spectre.Console/Rendering/Renderable.cs:line 22
   at Spectre.Console.Markup.Render(RenderContext context, Int32 maxWidth) in /_/src/Spectre.Console/Widgets/Markup.cs:line 59
   at Spectre.Console.Rendering.Renderable.Spectre.Console.Rendering.IRenderable.Render(RenderContext context, Int32 maxWidth) in /_/src/Spectre.Console/Rendering/Renderable.cs:line 22
   at Spectre.Console.TableRenderer.Render(TableRendererContext context, List`1 columnWidths) in /_/src/Spectre.Console/Widgets/Table/TableRenderer.cs:line 16
   at Spectre.Console.Table.Render(RenderContext context, Int32 maxWidth) in /_/src/Spectre.Console/Widgets/Table/Table.cs:line 177
   at Spectre.Console.Rendering.Renderable.Spectre.Console.Rendering.IRenderable.Render(RenderContext context, Int32 maxWidth) in /_/src/Spectre.Console/Rendering/Renderable.cs:line 22
   at Spectre.Console.RenderableExtensions.GetSegments(IAnsiConsole console, RenderContext options, IEnumerable`1 renderables) in /_/src/Spectre.Console/Extensions/RenderableExtensions.cs:line 39
   at Spectre.Console.RenderableExtensions.GetSegments(IRenderable renderable, IAnsiConsole console) in /_/src/Spectre.Console/Extensions/RenderableExtensions.cs:line 33
   at Spectre.Console.AnsiBuilder.Build(IAnsiConsole console, IRenderable renderable) in /_/src/Spectre.Console/Internal/Backends/Ansi/AnsiBuilder.cs:line 20
   at Spectre.Console.AnsiConsoleBackend.Write(IRenderable renderable) in /_/src/Spectre.Console/Internal/Backends/Ansi/AnsiConsoleBackend.cs:line 32
   at Spectre.Console.AnsiConsoleFacade.Write(IRenderable renderable) in /_/src/Spectre.Console/Internal/Backends/AnsiConsoleFacade.cs:line 43
   at Spectre.Console.AnsiConsole.Render(IRenderable renderable) in /_/src/Spectre.Console/AnsiConsole.Rendering.cs:line 22
...
```

**Comment by patriksvensson** [comment]
@phaselden I've been trying to recreate this but haven't succeeded. Do you think you could try to create a minimal reproducible example of this? All I would need is the table definition and the width of the console when the crash occurs.

**Comment by phaselden** [comment]
Sorry, I cannot recreate the issue either. It was no doubt a non-standard console width along with tables that have quite a few columns with wrapping text that created just the right circumstances to throw the error. 

If it occurs again I will attempt to capture some relevant info.

**Comment by LiamSho** [comment]
@phaselden Hi, I successfully recreate this issue. Using version 0.41.0 of Spectre.Console

https://user-images.githubusercontent.com/28832398/129158053-ed645237-b362-4e03-9371-2f491ddadcb5.mp4

Tested on Windows 11 build 22000.120 with cmd, Windows Terminal, Powershell Core 7 and Windows Powershell.

Also tested on macOS Monterey with Terminal.app (zsh with oh-my-zsh)

**Comment by LiamSho** [comment]
The question marks in the output is Japanese and Chinese character.

**Comment by patriksvensson** [comment]
@LiamSho That's great! Could you post the source code and the window width as well so we can recreate it?

**Comment by patriksvensson** [comment]
@LiamSho Thank you! I will take a look at it tonight.

**Comment by LiamSho** [comment]
@patriksvensson 

This is what I find. I am not a native English speaker, I will try my best to explain.

"これはテストタイトルです"
"这是很长很长的测试字符串"

Both of this Japanese string and Chinese string only have 12 characters, but its width is the same as 2 alphabets.
`Wcwidth.UnicodeCalculator.GetWidth(char value)` will return 2 if the value is any Japanese or Chinese character.

In my demo. "これはテストタイトルです" this string's total length is 24, but the max width of this column is 22.
[This line of code](https://github.com/spectreconsole/spectre.console/blob/main/src/Spectre.Console/Rendering/Segment.cs#L347) tries to cut the string and take 22 (max length) characters. But `string.Substring()` take 1 of Japanese or Chinese character as 1 character not 2. `"これはテストタイトルです".Substring(0, 22)` throw an `ArgumentOutOfRangeException`.

This exception will only be thrown when some characters' width is 2.

**Comment by phaselden** [comment]
@LiamSho That's fantastic. Excellent investigating! Thanks.
