### ISSUE TITLE
Prompt using select choices that containing brackets will throw

### ISSUE THREAD

**Issue by boxofyellow** [spectreconsole/spectre.console#608]
**Information**
 - OS: MacOS
 - Version: 10.15.7
 - Terminal: iTerm2

**Describe the bug**
Select choices that containing `[` (or `]`) can't be used even if they are escaped. 

**To Reproduce**
This little app displays the problem, I'm using  `<PackageReference Include="Spectre.Console" Version="0.42.0" />`

```
using Spectre.Console;

namespace Prompt
{
    class Program
    {
        static void Main() 
            => AnsiConsole.Prompt(new SelectionPrompt<int>()
                .UseConverter((i) => i switch
                    {
                        0 => "Zero",
                        //_ =>  $"[{i}",              // Without Escaping it blows up when the options are first displayed
                        _ => Markup.Escape($"[{i}"),  // With Escaping it blows up when you highlight the item
                    })
                .AddChoices(0, 1));
    }
}
```
If rum it will display 
```
> Zero
  [1
```
And it will throw if you press down to select the other value yielding this stack
```
~/test/Prompt > dotnet run
> Zero
  [1   Unhandled exception. System.InvalidOperationException: Encountered malformed markup tag at position 4.
   at Spectre.Console.MarkupTokenizer.MoveNext() in /_/src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs:line 83
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 23
   at Spectre.Console.SelectionPrompt`1.Spectre.Console.IListPromptStrategy<T>.Render(IAnsiConsole console, Boolean scrollable, Int32 cursorIndex, IEnumerable`1 items) in /_/src/Spectre.Console/Prompts/SelectionPrompt.cs:line 173
   at Spectre.Console.ListPrompt`1.BuildRenderable(ListPromptState`1 state) in /_/src/Spectre.Console/Prompts/List/ListPrompt.cs:line 113
   at Spectre.Console.ListPrompt`1.<>c__DisplayClass3_0.<Show>b__0() in /_/src/Spectre.Console/Prompts/List/ListPrompt.cs:line 47
   at Spectre.Console.ListPromptRenderHook`1.Process(RenderContext context, IEnumerable`1 renderables)+MoveNext() in /_/src/Spectre.Console/Prompts/List/ListPromptRenderHook.cs:line 45
   at Spectre.Console.RenderableExtensions.GetSegments(IAnsiConsole console, RenderContext options, IEnumerable`1 renderables) in /_/src/Spectre.Console/Extensions/RenderableExtensions.cs:line 39
   at Spectre.Console.RenderableExtensions.GetSegments(IRenderable renderable, IAnsiConsole console) in /_/src/Spectre.Console/Extensions/RenderableExtensions.cs:line 33
   at Spectre.Console.AnsiBuilder.Build(IAnsiConsole console, IRenderable renderable) in /_/src/Spectre.Console/Internal/Backends/Ansi/AnsiBuilder.cs:line 20
   at Spectre.Console.AnsiConsoleBackend.Write(IRenderable renderable) in /_/src/Spectre.Console/Internal/Backends/Ansi/AnsiConsoleBackend.cs:line 32
   at Spectre.Console.AnsiConsoleFacade.Write(IRenderable renderable) in /_/src/Spectre.Console/Internal/Backends/AnsiConsoleFacade.cs:line 43
   at Spectre.Console.ListPrompt`1.Show(ListPromptTree`1 tree, CancellationToken cancellationToken, Int32 requestedPageSize) in /_/src/Spectre.Console/Prompts/List/ListPrompt.cs:line 71
   at Spectre.Console.SelectionPrompt`1.ShowAsync(IAnsiConsole console, CancellationToken cancellationToken) in /_/src/Spectre.Console/Prompts/SelectionPrompt.cs:line 88
   at Spectre.Console.SelectionPrompt`1.Show(IAnsiConsole console) in /_/src/Spectre.Console/Prompts/SelectionPrompt.cs:line 80
   at Spectre.Console.AnsiConsole.Prompt[T](IPrompt`1 prompt) in /_/src/Spectre.Console/AnsiConsole.Prompt.cs:line 23
   at Prompt.Program.Main() in /Users/boxofyellow/test/Prompt/Program.cs:line 8
``` 

If you swap the commented out lines so that it does not escape the `[`, it will throw without displaying any options with this stack
```
~/test/Prompt > dotnet run
Unhandled exception. System.InvalidOperationException: Encountered malformed markup tag at position 4.
   at Spectre.Console.MarkupTokenizer.MoveNext() in /_/src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs:line 83
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 23
   at Spectre.Console.SelectionPrompt`1.Spectre.Console.IListPromptStrategy<T>.Render(IAnsiConsole console, Boolean scrollable, Int32 cursorIndex, IEnumerable`1 items) in /_/src/Spectre.Console/Prompts/SelectionPrompt.cs:line 173
   at Spectre.Console.ListPrompt`1.BuildRenderable(ListPromptState`1 state) in /_/src/Spectre.Console/Prompts/List/ListPrompt.cs:line 113
   at Spectre.Console.ListPrompt`1.<>c__DisplayClass3_0.<Show>b__0() in /_/src/Spectre.Console/Prompts/List/ListPrompt.cs:line 47
   at Spectre.Console.ListPromptRenderHook`1.Process(RenderContext context, IEnumerable`1 renderables)+MoveNext() in /_/src/Spectre.Console/Prompts/List/ListPromptRenderHook.cs:line 45
   at Spectre.Console.RenderableExtensions.GetSegments(IAnsiConsole console, RenderContext options, IEnumerable`1 renderables) in /_/src/Spectre.Console/Extensions/RenderableExtensions.cs:line 39
   at Spectre.Console.RenderableExtensions.GetSegments(IRenderable renderable, IAnsiConsole console) in /_/src/Spectre.Console/Extensions/RenderableExtensions.cs:line 33
   at Spectre.Console.AnsiBuilder.Build(IAnsiConsole console, IRenderable renderable) in /_/src/Spectre.Console/Internal/Backends/Ansi/AnsiBuilder.cs:line 20
   at Spectre.Console.AnsiConsoleBackend.Write(IRenderable renderable) in /_/src/Spectre.Console/Internal/Backends/Ansi/AnsiConsoleBackend.cs:line 32
   at Spectre.Console.AnsiConsoleCursor.Show(Boolean show) in /_/src/Spectre.Console/Internal/Backends/Ansi/AnsiConsoleCursor.cs:line 23
   at Spectre.Console.CursorExtensions.Hide(IAnsiConsoleCursor cursor) in /_/src/Spectre.Console/Extensions/CursorExtensions.cs:line 33
   at Spectre.Console.ListPrompt`1.Show(ListPromptTree`1 tree, CancellationToken cancellationToken, Int32 requestedPageSize) in /_/src/Spectre.Console/Prompts/List/ListPrompt.cs:line 51
   at Spectre.Console.SelectionPrompt`1.ShowAsync(IAnsiConsole console, CancellationToken cancellationToken) in /_/src/Spectre.Console/Prompts/SelectionPrompt.cs:line 88
   at Spectre.Console.SelectionPrompt`1.Show(IAnsiConsole console) in /_/src/Spectre.Console/Prompts/SelectionPrompt.cs:line 80
   at Spectre.Console.AnsiConsole.Prompt[T](IPrompt`1 prompt) in /_/src/Spectre.Console/AnsiConsole.Prompt.cs:line 23
   at Prompt.Program.Main() in /Users/boxofyellow/test/Prompt/Program.cs:line 8
~/test/Prompt >
```

**Expected behavior**
Throwing on the non-escaped `[` sounds reasonable, but when it has been escaped I would expect it be selectable. 

**Screenshots**

**Additional context**

**Comment by nils-a** [comment]
@boxofyellow thank you for reporting. I can confirm this behavior.
